#!/data/data/com.termux/files/usr/bin/bash
# gen_std.sh -- turns std/*.j (the standard library, written in J2K) into
# jcmp/jc_std.j, a function that puts the text in front of a program that says
# "import std". Run it after changing a file in std/, then ./bootstrap.sh.
cd "$(dirname "$0")"
python3 - <<'PY'
files = ["sys", "str", "math", "fs", "result", "collections"]
def gen(name, files, doc):
    out = ['void %s() {' % name,
           '    if lx_depth >= 15 { die("imports nested too deeply"); }',
           '    stk_pos[lx_depth] = cur_pos;', '    stk_line[lx_depth] = cur_line;',
           '    stk_ls[lx_depth] = cur_line_start;',
           '    str_copy(@lvl_name + (lx_depth + 1) * 128, @lvl_name + lx_depth * 128, 128);',
           '    lx_depth += 1;', '    cur_base = lx_depth * 524288;', '    cur_len = 0;']
    for f in files:
        for line in open("std/%s.j" % f).read().split("\n"):
            out.append('    put("%s");' % line.replace("\\", "\\\\").replace('"', '\\"'))
    out += ['    src_bufs[cur_base + cur_len] = 0;', '    cur_pos = 0;', '    cur_line = 1;',
            '    cur_line_start = 0;', '}', '']
    return ["// " + doc] + out
text = ['// jc_std.j -- GENERATED by gen_std.sh from std/*.j. Do not edit.', '']
text += gen("push_std", files, "push_std(): `import std` -- the standard library becomes a new \"file\" that is read next.")
text += gen("push_cpu", ["cpu"], "push_cpu(): `import cpu` -- threads and locks.")
text += gen("push_prelude", ["prelude"], "push_prelude(): read in front of every program (Mem and the dynamic array routines).")
open("jcmp/jc_std.j", "w").write("\n".join(text))
PY
